server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/auth/**, /api/customers/**

        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/api/restaurants/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**

        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/api/deliveries/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

app:
  jwt:
    secret: "myMonolithSecretKeyThatShouldBeExternalizedInMicroservices2024FoodDelivery!"
  rate-limiter:
    order-placement:
      limit-for-period: 20          # max requests per refresh window
      limit-refresh-period-seconds: 1

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.david.api_gateway: INFO
    org.springframework.cloud.gateway: WARN
